apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "22"
    meta.helm.sh/release-name: open5gs
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-06-07T18:10:51Z"
  generation: 194
  labels:
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: smf
    helm.sh/chart: smf-2.2.0
  name: open5gs-smf
  namespace: default
  resourceVersion: "30686726"
  uid: d6843e7f-9d03-4edf-a744-fa45fae756bd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: open5gs
      app.kubernetes.io/name: smf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-09-25T01:02:20Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: open5gs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: smf
        helm.sh/chart: smf-2.2.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: open5gs
                  app.kubernetes.io/name: smf
              namespaces:
              - default
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - open5gs-smfd
        image: docker.io/gradiant/open5gs:2.7.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: sbi
          timeoutSeconds: 5
        name: open5gs-smf
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        - containerPort: 8805
          name: pfcp
          protocol: UDP
        - containerPort: 2123
          name: gtpc
          protocol: UDP
        - containerPort: 2152
          name: gtpu
          protocol: UDP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: sbi
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 35m
          requests:
            cpu: 20m
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/smf.yaml
          name: config
          subPath: smf.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: open5gs-smf
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-06-07T18:22:21Z"
    lastUpdateTime: "2024-09-25T01:02:57Z"
    message: ReplicaSet "open5gs-smf-7c85bf5fd6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-11-06T18:30:35Z"
    lastUpdateTime: "2024-11-06T18:30:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 194
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
